import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'tutor',
  title: 'Tutors',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'professionalTitle',
      title: 'Professional Title & Education',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
      description: 'e.g., "Professional IB Tutor | University of Oxford | MSc Mathematics"',
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display Order',
      type: 'number',
      description: 'Controls the order in which tutors appear (lower numbers appear first). Set for both homepage and subject pages.',
      validation: (Rule: any) => Rule.required().precision(0).positive(),
      initialValue: 100,
    }),
    defineField({
      name: 'personallyInterviewed',
      title: 'Personally Interviewed',
      type: 'boolean',
      description: 'Show "Personally Interviewed" badge if checked',
      initialValue: false,
    }),
    defineField({
      name: 'displayOnHomepage',
      title: 'Display on Homepage',
      type: 'boolean',
      description: 'Show this tutor on the homepage',
      initialValue: false,
    }),
    defineField({
      name: 'displayOnSubjectPages',
      title: 'Display on Subject Pages',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'subjectPage' }] }],
      description: 'Select which subject pages this tutor should appear on',
    }),
    defineField({
      name: 'experience',
      title: 'Experience Description',
      type: 'text',
      validation: (Rule: any) => Rule.required(),
      description: 'Detailed description of teaching experience and approach',
    }),
    defineField({
      name: 'profilePhoto',
      title: 'Profile Photo',
      type: 'image',
      options: {
        hotspot: true,
      },
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'specialization',
      title: 'Specialization/Subject Area',
      type: 'object',
      validation: (Rule: any) => Rule.required(),
      fields: [
        {
          name: 'mainSubject',
          title: 'Main Subject',
          type: 'string',
          validation: (Rule: any) => Rule.required(),
          options: {
            list: [
              // IB Subjects
              'IB',
              'IB Maths',
              'IB English',
              'IB Biology',
              'IB Chemistry',
              'IB Physics',
              'IB Psychology',
              'IB Economics',
              'IB Business Management',
              'IB History',
              'IB Geography',
              'IB Extended Essay',
              'IB TOK',
              'IB Computer Science',
              'IB ESS',
              'IB Global Politics',
              'IB French',
              'IB German',
              'IB Italian',
              'IB Spanish',
              'IB MYP',
              // A-Level Subjects
              'A-Level',
              'A-Level Maths',
              'A-Level Further Maths',
              'A-Level Biology',
              'A-Level Chemistry',
              'A-Level Physics',
              'A-Level Psychology',
              'A-Level Computer Science',
              'A-Level English Literature',
              'A-Level Economics',
              'A-Level History',
              'A-Level Geography',
              'A-Level Business Studies',
              'A-Level French',
              'A-Level Spanish',
              'A-Level German',
              'A-Level Law',
              'A-Level Accounting',
              'A-Level EPQ',
              // IGCSE Subjects
              'IGCSE',
              'IGCSE Maths',
              'IGCSE English',
              'IGCSE Biology',
              'IGCSE Chemistry',
              'IGCSE Physics',
              'IGCSE Science',
              'IGCSE Computer Science',
              'IGCSE History',
              'IGCSE Geography',
              'IGCSE Business Studies',
              'IGCSE French',
              'IGCSE Spanish',
              'IGCSE German',
              // GCSE Subjects
              'GCSE',
              'GCSE Maths',
              'GCSE English',
              'GCSE Science',
              'GCSE Biology',
              'GCSE Chemistry',
              'GCSE Physics',
              'GCSE Computer Science',
              'GCSE History',
              'GCSE Geography',
              'GCSE Business Studies',
              'GCSE French',
              'GCSE Spanish',
              'GCSE German',
              // AP Subjects
              'AP',
              'AP Calculus AB/BC',
              'AP Biology',
              'AP Chemistry',
              'AP Physics',
              'AP Psychology',
              'AP Computer Science',
              'AP Statistics',
              'AP English Language',
              'AP English Literature',
              'AP Marcoeconomics & Microeconomics',
              'AP US History & World History',
              'AP Human Geography',
              'AP Spanish',
              // Standardized Tests
              'SAT',
              'ACT',
              'TSA',
              'STEP',
              'MAT',
              'PAT',
              'TMUA',
              'UCAT',
              'ESAT',
              'LNAT',
              // Admissions
              'Oxbridge',
              'US Admissions',
            ],
          },
        },
        {
          name: 'additionalSubjects',
          title: 'Additional Subjects',
          type: 'array',
          of: [{type: 'string'}],
          options: {
            list: [
              // IB Subjects
              'IB',
              'IB Maths',
              'IB English',
              'IB Biology',
              'IB Chemistry',
              'IB Physics',
              'IB Psychology',
              'IB Economics',
              'IB Business Management',
              'IB History',
              'IB Geography',
              'IB Extended Essay',
              'IB TOK',
              'IB Computer Science',
              'IB ESS',
              'IB Global Politics',
              'IB French',
              'IB German',
              'IB Italian',
              'IB Spanish',
              'IB MYP',
              // A-Level Subjects
              'A-Level',
              'A-Level Maths',
              'A-Level Further Maths',
              'A-Level Biology',
              'A-Level Chemistry',
              'A-Level Physics',
              'A-Level Psychology',
              'A-Level Computer Science',
              'A-Level English Literature',
              'A-Level Economics',
              'A-Level History',
              'A-Level Geography',
              'A-Level Business Studies',
              'A-Level French',
              'A-Level Spanish',
              'A-Level German',
              'A-Level Law',
              'A-Level Accounting',
              'A-Level EPQ',
              // IGCSE Subjects
              'IGCSE',
              'IGCSE Maths',
              'IGCSE English',
              'IGCSE Biology',
              'IGCSE Chemistry',
              'IGCSE Physics',
              'IGCSE Science',
              'IGCSE Computer Science',
              'IGCSE History',
              'IGCSE Geography',
              'IGCSE Business Studies',
              'IGCSE French',
              'IGCSE Spanish',
              'IGCSE German',
              // GCSE Subjects
              'GCSE',
              'GCSE Maths',
              'GCSE English',
              'GCSE Science',
              'GCSE Biology',
              'GCSE Chemistry',
              'GCSE Physics',
              'GCSE Computer Science',
              'GCSE History',
              'GCSE Geography',
              'GCSE Business Studies',
              'GCSE French',
              'GCSE Spanish',
              'GCSE German',
              // AP Subjects
              'AP',
              'AP Calculus AB/BC',
              'AP Biology',
              'AP Chemistry',
              'AP Physics',
              'AP Psychology',
              'AP Computer Science',
              'AP Statistics',
              'AP English Language',
              'AP English Literature',
              'AP Marcoeconomics & Microeconomics',
              'AP US History & World History',
              'AP Human Geography',
              'AP Spanish',
              // Standardized Tests
              'SAT',
              'ACT',
              'TSA',
              'STEP',
              'MAT',
              'PAT',
              'TMUA',
              'UCAT',
              'ESAT',
              'LNAT',
              // Admissions
              'Oxbridge',
              'US Admissions',
            ],
          },
        }
      ],
    }),
    defineField({
      name: 'yearsOfExperience',
      title: 'Years of Experience',
      type: 'number',
      validation: (Rule: any) => Rule.min(0),
    }),
    defineField({
      name: 'hireButtonLink',
      title: 'Hire Button Link',
      type: 'url',
      description: 'Link for the "Hire a Tutor" button. For subject pages, use /{slug}#contact-form format (e.g., "/online-dubai-english-tutor#contact-form"). For homepage, use "/#contact-form"',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'profilePDF',
      title: 'Profile PDF',
      type: 'file',
      description: 'PDF file that will be available through the "View Profile" button',
    }),
    defineField({
      name: 'price',
      title: 'Hourly Rate',
      type: 'object',
      description: 'Optional hourly rate information',
      fields: [
        {
          name: 'amount',
          title: 'Amount',
          type: 'number',
          description: 'The hourly rate amount',
        },
        {
          name: 'currency',
          title: 'Currency',
          type: 'string',
          description: 'The currency of the hourly rate',
          options: {
            list: [
              { title: 'AED (UAE Dirham)', value: 'AED' },
              { title: 'USD (US Dollar)', value: 'USD' },
              { title: 'GBP (British Pound)', value: 'GBP' },
              { title: 'EUR (Euro)', value: 'EUR' },
            ],
          },
        },
        {
          name: 'displayText',
          title: 'Display Text',
          type: 'string',
          description: 'Custom text to display for the price (e.g., "Starting from AED 200/hour")',
        }
      ],
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      type: 'number',
      description: 'Tutor rating (e.g., 4.8)',
      validation: (Rule: any) => Rule.min(0).max(5).precision(1),
    }),
    defineField({
      name: 'reviewCount',
      title: 'Number of Reviews',
      type: 'number',
      description: 'Total number of reviews received',
      validation: (Rule: any) => Rule.min(0).precision(0),
    }),
    defineField({
      name: 'activeStudents',
      title: 'Active Students',
      type: 'number',
      description: 'Number of current active students',
      validation: (Rule: any) => Rule.min(0).precision(0),
    }),
    defineField({
      name: 'totalLessons',
      title: 'Total Lessons',
      type: 'number',
      description: 'Total number of lessons conducted',
      validation: (Rule: any) => Rule.min(0).precision(0),
    }),
    defineField({
      name: 'languagesSpoken',
      title: 'Languages Spoken',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'language',
              title: 'Language',
              type: 'string',
            },
            {
              name: 'proficiency',
              title: 'Proficiency',
              type: 'string',
              options: {
                list: [
                  'Native',
                  'Fluent',
                  'Advanced',
                  'Intermediate',
                  'Basic'
                ]
              }
            }
          ],
          preview: {
            select: {
              language: 'language',
              proficiency: 'proficiency',
            },
            prepare({ language, proficiency }) {
              return {
                title: `${language} (${proficiency})`,
              }
            }
          }
        }
      ],
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'professionalTitle',
      media: 'profilePhoto',
    },
  },
}) 