import { defineField, defineType } from 'sanity'
import { addCloneSupport } from '../lib/cloneSchemaHelpers'

const tutorSchema = defineType({
  name: 'tutor',
  title: 'Tutors',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'professionalTitle',
      title: 'Professional Title & Education',
      type: 'string',
      description: 'e.g., "Professional IB Tutor | University of Oxford | MSc Mathematics"',
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display Order',
      type: 'number',
      description: 'Controls the order in which tutors appear (lower numbers appear first). Set for both homepage and subject pages.',
      validation: (Rule: any) => Rule.required().precision(0).positive(),
      initialValue: 100,
    }),

    defineField({
      name: 'displayOnHomepage',
      title: 'Display on Homepage',
      type: 'boolean',
      description: 'Show this tutor on the homepage',
      initialValue: false,
    }),
    defineField({
      name: 'displayOnSubjectPages',
      title: 'Display on Subject Pages',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'subjectPage' }] }],
      description: 'Select which subject pages this tutor should appear on',
    }),
    defineField({
      name: 'experience',
      title: 'Experience Description',
      type: 'text',
      validation: (Rule: any) => Rule.required(),
      description: 'Detailed description of teaching experience and approach',
    }),
    defineField({
      name: 'profilePhoto',
      title: 'Profile Photo',
      type: 'image',
      options: {
        hotspot: true,
      },
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'specialization',
      title: 'Specialization/Subject Area',
      type: 'object',
      validation: (Rule: any) => Rule.required(),
      fields: [
        {
          name: 'mainSubject',
          title: 'Main Subject',
          type: 'string',
          validation: (Rule: any) => Rule.required(),
          options: {
            list: [
              // IB Subjects
              'IB',
              'IB Maths',
              'IB English',
              'IB Biology',
              'IB Chemistry',
              'IB Physics',
              'IB Psychology',
              'IB Economics',
              'IB Business Management',
              'IB History',
              'IB Geography',
              'IB Extended Essay',
              'IB TOK',
              'IB Computer Science',
              'IB ESS',
              'IB Global Politics',
              'IB French',
              'IB German',
              'IB Italian',
              'IB Spanish',
              'IB MYP',
              // A-Level Subjects
              'A-Level',
              'A-Level Maths',
              'A-Level Further Maths',
              'A-Level Biology',
              'A-Level Chemistry',
              'A-Level Physics',
              'A-Level Psychology',
              'A-Level Computer Science',
              'A-Level English Literature',
              'A-Level Economics',
              'A-Level History',
              'A-Level Geography',
              'A-Level Business Studies',
              'A-Level French',
              'A-Level Spanish',
              'A-Level German',
              'A-Level Law',
              'A-Level Accounting',
              'A-Level EPQ',
              // IGCSE Subjects
              'IGCSE',
              'IGCSE Maths',
              'IGCSE English',
              'IGCSE Biology',
              'IGCSE Chemistry',
              'IGCSE Physics',
              'IGCSE Science',
              'IGCSE Computer Science',
              'IGCSE History',
              'IGCSE Geography',
              'IGCSE Business Studies',
              'IGCSE French',
              'IGCSE Spanish',
              'IGCSE German',
              // GCSE Subjects
              'GCSE',
              'GCSE Maths',
              'GCSE English',
              'GCSE Science',
              'GCSE Biology',
              'GCSE Chemistry',
              'GCSE Physics',
              'GCSE Computer Science',
              'GCSE History',
              'GCSE Geography',
              'GCSE Business Studies',
              'GCSE French',
              'GCSE Spanish',
              'GCSE German',
              // AP Subjects
              'AP',
              'AP Calculus AB/BC',
              'AP Biology',
              'AP Chemistry',
              'AP Physics',
              'AP Psychology',
              'AP Computer Science',
              'AP Statistics',
              'AP English Language',
              'AP English Literature',
              'AP Macroeconomics & Microeconomics',
              'AP US History & World History',
              'AP Human Geography',
              'AP Spanish',
              // Standardized Tests
              'SAT',
              'ACT',
              'TSA',
              'STEP',
              'MAT',
              'PAT',
              'TMUA',
              'UCAT',
              'ESAT',
              'LNAT',
              // Admissions
              'Oxbridge',
              'US Admissions',
              // Additional Curricula
              'HSC',
              'HSC Maths',
              'HSC English',
              'HSC Biology',
              'HSC Chemistry',
              'HSC Physics',
              'HSC Business',
              'HSC Economics',
              'HSC History',
              'HSC Geography',
              'HSC Psychology',
              'VCE',
              'VCE Maths',
              'VCE English',
              'VCE Biology',
              'VCE Chemistry',
              'VCE Physics',
              'VCE Business',
              'VCE Economics',
              'VCE History',
              'VCE Geography',
              'VCE Psychology',
              'QCE',
              'QCE Maths',
              'QCE English',
              'QCE Biology',
              'QCE Chemistry',
              'QCE Physics',
              'QCE Business',
              'QCE Economics',
              'QCE History',
              'QCE Geography',
              'QCE Psychology',
              'OSSD',
              'OSSD Maths',
              'OSSD English',
              'OSSD Biology',
              'OSSD Chemistry',
              'OSSD Physics',
              'OSSD Business',
              'OSSD Economics',
              'OSSD History',
              'OSSD Geography',
              'OSSD Psychology',
              'BC',
              'BC Maths',
              'BC English',
              'BC Biology',
              'BC Chemistry',
              'BC Physics',
              'BC Business',
              'BC Economics',
              'BC History',
              'BC Geography',
              'BC Psychology',
              'DES',
              'DES Maths',
              'DES English',
              'DES Biology',
              'DES Chemistry',
              'DES Physics',
              'DES Business',
              'DES Economics',
              'DES History',
              'DES Geography',
              'DES Psychology',
              // Alberta Subjects
              'Alberta',
              'Alberta Maths',
              'Alberta English',
              'Alberta Biology',
              'Alberta Chemistry',
              'Alberta Physics',
              'Alberta Business',
              'Alberta Economics',
              'Alberta History',
              'Alberta Geography',
              'Alberta Psychology',
            ],
          },
        },
        {
          name: 'additionalSubjects',
          title: 'Additional Subjects',
          type: 'array',
          of: [{type: 'string'}],
          options: {
            list: [
              // IB Subjects
              'IB',
              'IB Maths',
              'IB English',
              'IB Biology',
              'IB Chemistry',
              'IB Physics',
              'IB Psychology',
              'IB Economics',
              'IB Business Management',
              'IB History',
              'IB Geography',
              'IB Extended Essay',
              'IB TOK',
              'IB Computer Science',
              'IB ESS',
              'IB Global Politics',
              'IB French',
              'IB German',
              'IB Italian',
              'IB Spanish',
              'IB MYP',
              // A-Level Subjects
              'A-Level',
              'A-Level Maths',
              'A-Level Further Maths',
              'A-Level Biology',
              'A-Level Chemistry',
              'A-Level Physics',
              'A-Level Psychology',
              'A-Level Computer Science',
              'A-Level English Literature',
              'A-Level Economics',
              'A-Level History',
              'A-Level Geography',
              'A-Level Business Studies',
              'A-Level French',
              'A-Level Spanish',
              'A-Level German',
              'A-Level Law',
              'A-Level Accounting',
              'A-Level EPQ',
              // IGCSE Subjects
              'IGCSE',
              'IGCSE Maths',
              'IGCSE English',
              'IGCSE Biology',
              'IGCSE Chemistry',
              'IGCSE Physics',
              'IGCSE Science',
              'IGCSE Computer Science',
              'IGCSE History',
              'IGCSE Geography',
              'IGCSE Business Studies',
              'IGCSE French',
              'IGCSE Spanish',
              'IGCSE German',
              // GCSE Subjects
              'GCSE',
              'GCSE Maths',
              'GCSE English',
              'GCSE Science',
              'GCSE Biology',
              'GCSE Chemistry',
              'GCSE Physics',
              'GCSE Computer Science',
              'GCSE History',
              'GCSE Geography',
              'GCSE Business Studies',
              'GCSE French',
              'GCSE Spanish',
              'GCSE German',
              // AP Subjects
              'AP',
              'AP Calculus AB/BC',
              'AP Biology',
              'AP Chemistry',
              'AP Physics',
              'AP Psychology',
              'AP Computer Science',
              'AP Statistics',
              'AP English Language',
              'AP English Literature',
              'AP Macroeconomics & Microeconomics',
              'AP US History & World History',
              'AP Human Geography',
              'AP Spanish',
              // Standardized Tests
              'SAT',
              'ACT',
              'TSA',
              'STEP',
              'MAT',
              'PAT',
              'TMUA',
              'UCAT',
              'ESAT',
              'LNAT',
              // Admissions
              'Oxbridge',
              'US Admissions',
              // Additional Curricula
              'HSC',
              'HSC Maths',
              'HSC English',
              'HSC Biology',
              'HSC Chemistry',
              'HSC Physics',
              'HSC Business',
              'HSC Economics',
              'HSC History',
              'HSC Geography',
              'HSC Psychology',
              'VCE',
              'VCE Maths',
              'VCE English',
              'VCE Biology',
              'VCE Chemistry',
              'VCE Physics',
              'VCE Business',
              'VCE Economics',
              'VCE History',
              'VCE Geography',
              'VCE Psychology',
              'QCE',
              'QCE Maths',
              'QCE English',
              'QCE Biology',
              'QCE Chemistry',
              'QCE Physics',
              'QCE Business',
              'QCE Economics',
              'QCE History',
              'QCE Geography',
              'QCE Psychology',
              'OSSD',
              'OSSD Maths',
              'OSSD English',
              'OSSD Biology',
              'OSSD Chemistry',
              'OSSD Physics',
              'OSSD Business',
              'OSSD Economics',
              'OSSD History',
              'OSSD Geography',
              'OSSD Psychology',
              'BC',
              'BC Maths',
              'BC English',
              'BC Biology',
              'BC Chemistry',
              'BC Physics',
              'BC Business',
              'BC Economics',
              'BC History',
              'BC Geography',
              'BC Psychology',
              'DES',
              'DES Maths',
              'DES English',
              'DES Biology',
              'DES Chemistry',
              'DES Physics',
              'DES Business',
              'DES Economics',
              'DES History',
              'DES Geography',
              'DES Psychology',
              // Alberta Subjects
              'Alberta',
              'Alberta Maths',
              'Alberta English',
              'Alberta Biology',
              'Alberta Chemistry',
              'Alberta Physics',
              'Alberta Business',
              'Alberta Economics',
              'Alberta History',
              'Alberta Geography',
              'Alberta Psychology',
            ],
          },
        }
      ],
    }),

    defineField({
      name: 'hireButtonLink',
      title: 'Hire Button Link',
      type: 'url',
      description: 'Link for the "Hire a Tutor" button. For subject pages, use /{slug}#contact-form format (e.g., "/online-dubai-english-tutor#contact-form"). For homepage, use "/#contact-form"',
      validation: (Rule: any) => Rule.required().uri({ allowRelative: true, scheme: ['http', 'https'] }),
    }),

    defineField({
      name: 'price',
      title: 'Hourly Rate',
      type: 'object',
      description: 'Optional hourly rate information',
      fields: [
        {
          name: 'amount',
          title: 'Price Amount',
          type: 'string',
          description: 'Price with currency (e.g., "AED 200", "from USD 150")',
        },
        {
          name: 'unit',
          title: 'Price Unit',
          type: 'string',
          description: 'Time unit (e.g., "hr", "/hour", "per hour")',
        }
      ],
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      type: 'number',
      description: 'Tutor rating (e.g., 4.8)',
      validation: (Rule: any) => Rule.min(0).max(5).precision(1),
    }),

    defineField({
      name: 'activeStudents',
      title: 'Active Students',
      type: 'number',
      description: 'Number of current active students',
      validation: (Rule: any) => Rule.min(0).precision(0),
    }),


  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'professionalTitle',
      media: 'profilePhoto',
    },
  },
})

export default addCloneSupport(tutorSchema) 